# Usa una imagen más ligera basada en Alpine
FROM node:16-alpine

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código
COPY . .

# Expone el puerto
EXPOSE 3000

# Comando para iniciar el servidor de desarrollo de Vite
CMD ["npm", "run", "dev"]
