name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/ubuntu/SwiftShop"
          port: 22
          timeout: 60s # Aumentar el tiempo de espera
          use_insecure_cipher: false

      - name: Execute commands via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          debug: true
          timeout: 60s # Aumenta el tiempo de espera
          command_timeout: 20m # Aumenta el tiempo de espera para ejecutar comandos
          script: |
            # Navega al directorio de tu proyecto en EC2
            cd /home/ubuntu/SwiftShop

            # Actualiza el repositorio desde GitHub
            git pull origin main

            # Backend deployment
            cd /home/ubuntu/SwiftShop/backend
            npm install  # Instala dependencias de backend
            pm2 restart backend  # Reinicia el backend (usa pm2 o el sistema que estés utilizando)

            # Frontend deployment
            cd /home/ubuntu/SwiftShop/frontend
            npm install  # Instala dependencias de frontend
            npm run build  # Compila el frontend

            # Copia los archivos compilados a la carpeta que Nginx utiliza para servir el frontend
            sudo cp -r /home/ubuntu/SwiftShop/frontend/dist/* /var/www/html/

            # Verifica la configuración de Nginx
            sudo nginx -t

            # Reinicia Nginx
            sudo systemctl restart nginx
