name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Execute commands via SSH
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu # Usuario adecuado para la instancia
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/SwiftShop
            git pull origin main  # Actualiza el código desde GitHub

            # Backend deployment
            cd /home/ubuntu/SwiftShop/backend
            npm install  # Instala dependencias del backend
            pm2 restart backend  # Reinicia el backend

            # Frontend deployment
            cd /home/ubuntu/SwiftShop/frontend
            npm install  # Instala dependencias del frontend
            npm run build  # Compila el frontend

            # Copia los archivos compilados a la carpeta que Nginx utiliza para servir el frontend
            sudo cp -r /home/ubuntu/SwiftShop/frontend/dist/* /var/www/html/

            # Verifica la configuración de Nginx y reinicia el servicio
            sudo nginx -t
            sudo systemctl restart nginx
