name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/ubuntu/SwiftShop"

      - name: Execute commands via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navega al directorio de tu proyecto en EC2
            cd /home/ubuntu/SwiftShop
            # Actualiza el repositorio desde GitHub
            git pull origin main
            # Backend deployment
            cd backend
            npm install
            pm2 restart backend
            # Frontend deployment
            cd ../frontend
            # Asegúrate de que el usuario tenga permisos de escritura en la carpeta dist
            sudo chown -R $USER:$USER /home/ubuntu/SwiftShop/frontend/dist
            sudo chmod -R 755 /home/ubuntu/SwiftShop/frontend/dist
            # Instala dependencias y compila el frontend
            npm install
            npm run build
            # Copia los archivos compilados a la carpeta que Nginx utiliza para servir el frontend
            sudo cp -r /home/ubuntu/SwiftShop/frontend/dist/* /var/www/html/
            # Verifica la configuración de Nginx
            sudo nginx -t
            # Reinicia Nginx
            sudo systemctl restart nginx
