name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v2

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install SSH Key
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Navega al directorio de tu proyecto en EC2
            cd /home/ubuntu/SwiftShop

            # Actualiza el repositorio desde GitHub
            git pull origin main

            # Backend deployment
            cd /home/ubuntu/SwiftShop/backend
            npm install  # Instala dependencias de backend
            pm2 restart backend  # Reinicia el backend (usa pm2 o el sistema que estés utilizando)

            # Frontend deployment
            cd /home/ubuntu/SwiftShop/frontend
            npm install  # Instala dependencias de frontend
            npm run build  # Compila el frontend

            # Copia los archivos compilados a la carpeta que Nginx utiliza para servir el frontend
            sudo cp -r /home/ubuntu/SwiftShop/frontend/dist/* /var/www/html/

            # Verifica la configuración de Nginx
            sudo nginx -t

            # Reinicia Nginx
            sudo systemctl restart nginx
